name: Publish Canary Releases

on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main

env:
  # See https://consoledonottrack.com/
  DO_NOT_TRACK: '1'

jobs:
  build-and-publish-snapshots-to-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Run Test & Lint
        run: pnpm test

      - name: Run Build Step
        run: pnpm build

      - name: Configure NPM token
        run: |
          pnpm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Canary Release
        run: |
          pnpm pkg delete devDependencies
          pnpm changeset version --snapshot canary
          pnpm build
          pnpm publish-packages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PUBLISH_TAG: canary
