name: Pull requests

on:
  pull_request:

env:
  # Among other things, opts out of Turborepo telemetry
  # See https://consoledonottrack.com/
  DO_NOT_TRACK: '1'
  # Some tasks slow down considerably on GitHub Actions runners when concurrency is high
  TURBO_CONCURRENCY: 1

jobs:
  # Needed for grouping check-web3 strategies into one check for mergify
  all-pr-checks:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - run: echo "Done"

  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node:
          - 'current'
          - 'lts/*'

    name: Build & Test on Node ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies
        with:
          version: ${{ matrix.node }}

      - name: Build
        run: pnpm build

      - name: Test & Lint
        run: pnpm test
